# Generated by Django 4.0.3 on 2022-03-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0013_alter_produkt_data_dodania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='kategoria_id',
            new_name='kategoria',
        ),
    ]
