# Generated by Django 4.0.3 on 2022-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0015_alter_produkt_data_modyfikacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='abc', null=True, upload_to='moja_sciezka/'),
        ),
    ]
