# Generated by Django 4.0.3 on 2022-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0017_alter_produkt_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='domyslna_sciezka', null=True, upload_to='moja_sciezka/'),
        ),
    ]
