# Generated by Django 4.0.3 on 2022-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0018_alter_produkt_opis_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default='opis_domyśłny', null=True),
        ),
    ]
