# Generated by Django 4.0.3 on 2022-03-09 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0020_alter_produkt_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='data_dodania',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
