# Generated by Django 4.0.3 on 2022-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0022_alter_produkt_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(null=True),
        ),
    ]
