# Generated by Django 4.0.3 on 2022-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0024_alter_produkt_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(default='zero', max_length=300, unique_for_date=True),
        ),
    ]
