# Generated by Django 4.0.3 on 2022-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0027_alter_produkt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='data_dodania'),
        ),
    ]
