# Generated by Django 4.0.3 on 2022-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0028_alter_produkt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default='opis_domyślny'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(max_length=300,),
        ),
    ]
