# Generated by Django 4.0.3 on 2022-03-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0029_alter_produkt_opis_alter_produkt_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='slug',
        ),
    ]
