# Generated by Django 4.0.3 on 2022-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0035_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='domyslna_sciezka', null=True, upload_to='\\Users\\LucWr\\Desktop\\telefon\\!posegregowane\\20200710-Bieszczady z Jadzią Łabą\\/'),
        ),
    ]
