# Generated by Django 4.0.3 on 2022-03-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0039_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.email'),
        ),
    ]
