# Generated by Django 4.0.3 on 2022-03-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0042_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_id',
        ),
    ]
