# Generated by Django 4.0.3 on 2022-03-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0043_rename_email_user_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koszyk_login',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adres',
            new_name='adres_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.email'),
        ),
    ]
