# Generated by Django 4.0.3 on 2022-03-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0046_rename_mail_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszyk_login',
            name='nr_zamowienia',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
