# Generated by Django 4.0.3 on 2022-03-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0047_alter_koszyk_login_nr_zamowienia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszyk_logout',
            name='nr_zamowienia',
            field=models.CharField(max_length=17),
        ),
    ]
